In [2]:
import numpy as np
import itertools
from molmass import ELEMENTS
import project_01 as p1

In [5]:
mol = p1.Molecule()
file = 'input/acetaldehyde.dat'
mol.read_dat(file)
print(mol.charges)

[6 6 8 1 1 1 1]


In [15]:
com = mol.center_of_mass()
print(com)

[0.64475065 0.         2.31636762]


In [16]:
trans_coords = mol.coordinates - com
print(mol.coordinates)
print(trans_coords)
weights = np.array([ELEMENTS[charge].mass for charge in mol.charges])

[[ 0.          0.          0.        ]
 [ 0.          0.          2.84511213]
 [ 1.89911596  0.          4.13906253]
 [-1.89404831  0.          3.74768867]
 [ 1.94250082  0.         -0.70114598]
 [-1.00729547 -1.66997184 -0.70591697]
 [-1.00729547  1.66997184 -0.70591697]]
[[-0.64475065  0.         -2.31636762]
 [-0.64475065  0.          0.52874451]
 [ 1.25436532  0.          1.82269491]
 [-2.53879895  0.          1.43132105]
 [ 1.29775017  0.         -3.0175136 ]
 [-1.65204611 -1.66997184 -3.02228459]
 [-1.65204611  1.66997184 -3.02228459]]


In [41]:
tensor = - np.einsum('i, ix, iy -> xy', weights, trans_coords, trans_coords)
print(tensor)
np.trace(tensor)
np.trace(abs(tensor))

[[ -48.85586414   -0.          -52.87851329]
 [  -0.           -5.62190373   -0.        ]
 [ -52.87851329   -0.         -150.61179651]]


205.08956437777633

In [42]:
np.fill_diagonal(tensor, tensor.diagonal() + np.trace(np.abs(tensor)))
tensor
np.linalg.eigvalsh(tensor)


array([ 31.97518751, 178.73628059, 199.46766065])

In [3]:
mol.print_bond_angles()
mol.print_bond_lengths()
mol.print_oop_angles()
mol.print_dihedral_angles()
print('===Center of Mass===')
print('{:3.8e} {:3.8e} {:3.8e}'.format(*mol.center_of_mass()))
mol.print_moment_of_inertia()
print(f'Type of inertia: {mol.type_of_inertia()}')
print(f'Rotational constants in cm^-1: {mol.rotational_constants()}')
print(f'Rotational constants in MHz: {mol.rotational_constants() / 1000}')

===Bond Angle===
(0, 1, 2): 124.26830826072018 degrees
(0, 1, 3): 115.4793409840136 degrees
(1, 0, 4): 109.84705594988364 degrees
(1, 0, 5): 109.89840610470087 degrees
(1, 0, 6): 109.89840610470087 degrees
(2, 1, 3): 120.25235075526628 degrees
(4, 0, 5): 109.95368230959265 degrees
(4, 0, 6): 109.95368230959265 degrees
(5, 0, 6): 107.25264587722444 degrees
===Bond Length===
  0 - 1:      2.84511 Bohr
  0 - 2:      4.55395 Bohr
  0 - 3:      4.19912 Bohr
  0 - 4:      2.06517 Bohr
  0 - 5:      2.07407 Bohr
  0 - 6:      2.07407 Bohr
  1 - 2:      2.29803 Bohr
  1 - 3:      2.09811 Bohr
  1 - 4:      4.04342 Bohr
  1 - 5:      4.05133 Bohr
  1 - 6:      4.05133 Bohr
  2 - 3:      3.81330 Bohr
  2 - 4:      4.84040 Bohr
  2 - 5:      5.89151 Bohr
  2 - 6:      5.89151 Bohr
  3 - 4:      5.87463 Bohr
  3 - 5:      4.83836 Bohr
  3 - 6:      4.83836 Bohr
  4 - 5:      3.38971 Bohr
  4 - 6:      3.38971 Bohr
  5 - 6:      3.33994 Bohr
===Out of Plane Angle===
(0, 2, 1, 3): 0.0 degrees
(1, 4,